sudo: required
services:
  - docker

before_install:
  - docker build -t adamgitlab/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adamgitlab/react-test npm test

after_success:
  - docker build -t adamgitlab/multi-client ./client
  - docker build -t adamgitlab/multi-nginx ./nginx
  - docker build -t adamgitlab/multi-server ./server
  - docker build -t adamgitlab/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adamgitlab/multi-client
  - docker push adamgitlab/multi-nginx
  - docker push adamgitlab/multi-server
  - docker push adamgitlab/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-591674499168'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
